version: '3.8'

services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_CLIENT_PORT_ADDRESS: 0.0.0.0
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
    networks:
      - edge-network

  zookeeper2:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2182:2182"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_CLIENT_PORT_ADDRESS: 0.0.0.0
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
    networks:
      - edge-network
  
  zookeeper3:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2183:2183"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_CLIENT_PORT_ADDRESS: 0.0.0.0
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zoozookeeper2:2888:3888;zookeeper3:2888:3888
    networks:
      - edge-network


  # Edge Services
  edge1:
    build:
      context: .
      dockerfile: Edge/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      AppSettings__CONTAINER_NAME: edge1
      AppSettings__ZOOKEEPER_HOST: zookeeper1:2181, zookeeper2:2182, zookeeper3:2183
      AppSettings__EDGE_HOST: http://localhost:8080
    volumes:
      - ./Edge:/app/release
    networks:
      - edge-network

  edge2:
    build:
      context: .
      dockerfile: Edge/Dockerfile
    ports:
      - "8085:8085"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8085
      AppSettings__CONTAINER_NAME: edge2
      AppSettings__ZOOKEEPER_HOST: zookeeper1:2181, zookeeper2:2182, zookeeper3:2183
      AppSettings__EDGE_HOST: http://localhost:8085
    volumes:
      - ./Edge:/app/release
    networks:
      - edge-network

  edge3:
    build:
      context: .
      dockerfile: Edge/Dockerfile
    ports:
      - "8090:8090"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8090
      AppSettings__CONTAINER_NAME: edge3
      AppSettings__ZOOKEEPER_HOST: zookeeper1:2181, zookeeper2:2182, zookeeper3:2183
      AppSettings__EDGE_HOST: http://localhost:8090
    volumes:
      - ./Edge:/app/release
    networks:
      - edge-network

  edge4:
    build:
      context: .
      dockerfile: Edge/Dockerfile
    ports:
      - "8095:8095"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8095
      AppSettings__CONTAINER_NAME: edge4
      AppSettings__ZOOKEEPER_HOST: zookeeper1:2181, zookeeper2:2182, zookeeper3:2183
      AppSettings__EDGE_HOST: http://localhost:8095
    volumes:
      - ./Edge:/app/release
    networks:
      - edge-network

networks:
  edge-network: # Özel ağ tanımı
    driver: bridge
