{
 "title": "Avaliblity",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Edge-1 CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "edge_cpu{node=\"edge1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Edge-2 CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "edge_cpu{node=\"edge2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Edge-3 CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "edge_cpu{node=\"edge3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Edge-4 CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "edge_cpu{node=\"edge4\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Edge-1 Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "edge_status{node=\"edge1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Edge-2 Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "edge_status{node=\"edge2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Edge-3 Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "edge_status{node=\"edge3\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Edge-4 Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "edge_status{node=\"edge4\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}